version: '3'

services:
  application-service:
    build: .
    restart: always
    volumes: 
      - /var/lib/application/images:/var/lib/application/images
    ports:
      - 8080:8080
    depends_on:
      - application-database
    environment:
      - DB_SERVER=application-database
      - DB_PASSWORD=password
      - DB_USERNAME=postgres
      - DB_DATABASE=mydb
      - UPLOAD_DIR=/var/lib/application/images
    links:
      - application-database

  application-database:
    image: postgres
    restart: always
    volumes:
      - /var/lib/application/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb