version: '3'

services:
  application-service:
    build: .
    restart: always
    volumes: 
      - imagevolume:/tmp/image_upload
    ports:
      - 8080:8080
    depends_on:
      - application-database
    environment:
      - DB_SERVER=application-database
      - DB_PASSWORD=password
      - DB_USERNAME=postgres
      - DB_DATABASE=mydb
      - UPLOAD_DIR=/tmp/image_upload
    links:
      - application-database

  application-database:
    image: postgres
    restart: always
    volumes:
      - dbvolume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb

  application-proxy:
    image: staticfloat/nginx-certbot
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: grzegorzbujak10@gmail.com
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
      - imagevolume:/tmp/image_upload

volumes:
  letsencrypt:
  dbvolume:
  imagevolume: